# Generated by Django 4.1 on 2022-09-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre de la marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'db_table': 'marca',
                'ordering': ['id'],
            },
        ),
    ]
